title: "Developer-Fast-Track"
description: "Criar um ambiente de cloud native através de terraform e Resource Manager"
schemaVersion: 1.1.0
version: "20190304"
locale: "pt-br"


#################
# Variaveis
#################
variableGroups:
- title: Configuração Geral
  visible: false
  variables:
  - tenancy_ocid
  - region
  - node_pool_boot_volume_size_in_gbs
  - oke_compartment_description
  - user_ocid
  - fingerprint
  - private_key_path
  - network_cidrs
  - cluster_options_admission_controller_options_is_pod_security_policy_enabled
  - deploy_pipeline_deploy_pipeline_parameters_items_default_value
  - deploy_pipeline_deploy_pipeline_parameters_items_description
  - deploy_pipeline_deploy_pipeline_parameters_items_name
  - release

- title: Projeto DevOps
  visible: true  
  variables:
    - compartment_id
    - app_name
    - show_advanced
    - log_group_display_name
    - notification_topic_name
    - project_description
    - project_logging_config_display_name_prefix
    - project_logging_config_is_archiving_enabled
    - project_logging_config_retention_period_in_days

- title: Ambiente DevOps
  visible: 
      and:
        - show_advanced
  variables:
    - environment_type 
    - environment_description 
    - environment_display_name

- title: Configuração de Políticas
  description: Configuração de Políticas para a implementação do stack
  visible: true  
  variables:
    - create_dynamic_group_for_devops_pipln_in_compartment
    - create_dynamic_group_for_nodes_in_compartment
    - existent_dynamic_group_for_nodes_in_compartment
    - create_compartment_policies
    - create_tenancy_policies
    
- title: Configuração de Criptografia
  description: Configuração de Políticas para a implementação do stack
  visible: true  
  variables:
    - use_encryption_from_oci_vault
    - create_new_encryption_key
    - existent_encryption_key_id
    - create_vault_policies_for_group
    - user_admin_group_for_vault_policy

- title: "OKE Worker Nodes"
  variables:
    - num_pool_workers
    - node_pool_shape
    - node_pool_node_shape_config_ocpus
    - node_pool_node_shape_config_memory_in_gbs
    - node_pool_name
    - k8s_version

- title: "API Gateway"
  visible: true
  variables:
    - api_gateway_name
    - api_gateway_type

- title: "Repository"
  visible: true
  variables:
   - repository_is_immutable
   - repository_repository_type
   - artifact_repository_display_name
   - container_repository_display_name 

- title: "Functions"
  visible: true
  variables:
   - application_display_name

- title: "Queue"
  visible: true
  variables:
    - queue_display_name

- title: "Vault"
  visible: true
  variables:
    - vault_display_name

#################
# Output Groups
#################
outputGroups:
- title: Service Endpoints
  outputs:
    - theia_public_ip
- title: Generated Passwords
  outputs:
    - generated_ssh_private_key

outputs:
  theia_public_ip:
    type: link
    title: Your Theia website
    description: Open Theia website
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    description: "Generated SSH Private Key"
    type: copyableString
    visible: true

primaryOutputButton: theia_public_ip


######################
# Variable Definitions
######################

variables:

  compartment_id: 
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create resources"
    required: true

  app_name:
    type: string
    title: "Project Name"
    required: true
  
  show_advanced:
    type: boolean
    title: "Mostrar opções avançadas?"
    description: "Mostra opções avançadas, permitindo habilitar chaves de criptografia gerenciadas pelo cliente, selecionar sua chave ssh, selecionar/desmarcar utilitários de cluster, não criar políticas e outras opções avançadas"
    visible: true
    default: false

## DevOps

  log_group_display_name:
    type: string
    title: "Nome do grupo de logs"
    description: "Nome de exibição para o grupo de logs"
    default: "devops-logs"
    required: true
    visible: 
      and:
        - show_advanced

  notification_topic_name:
    type: string
    title: "Nome do Notification Topic"
    description: "Nome do notification topic usado para mensagens sobre o projeto"
    default: "devops-topic"
    required: true
    visible: 
      and:
        - show_advanced


  project_description:
    type: string
    title: "Descrição do projeto DevOps"
    description: "Uma breve descrição do projeto DevOps"
    default: "Projeto DevOps para implantação OKE"
    required: true
    visible: 
      and:
        - show_advanced


  project_logging_config_display_name_prefix:
    type: string
    title: "Prefixo para configuração do Logging"
    description: "Nome de exibição para o grupo de logs"
    default: "FT-"
    required: true
    visible: 
      and:
        - show_advanced

  project_logging_config_is_archiving_enabled:
    type: boolean
    title: "Arquivamento habilitado para registro de projetos"
    description: "Nome de exibição para o grupo de logs"
    default: false
    required: true
    visible: 
      and:
        - show_advanced

  project_logging_config_retention_period_in_days:
    type: string
    title: "Período de retenção dos logs do projeto"
    description: "Dias para reter os logs do Projeto."
    default: 30
    required: true
    visible: 
      and:
        - show_advanced
  
  #############
  # Environment
  ############# 

  environment_type:
    type: enum
    enum:
      - "OKE_CLUSTER"
    title: "Tipo de ambiente"
    description: "O tipo de ambiente a ser direcionado. A pilha atualmente suporta apenas OKE_CLUSTER"
    default: "OKE_CLUSTER"
    visible: 
      and:
        - show_advanced
  environment_description:
    type: string
    title: "Descrição do ambiente"
    description: "Descrever o ambiente DevOps"
    default: "Ambiente OKE que pode ser direcionado por DevOps"
    visible: 
      and:
        - show_advanced
  environment_display_name:
    type: string
    title: "Nome do ambiente"
    description: "Nome para o ambiente DevOps"
    default: "DevOps OKE Environment"
  
  ###########
  # Pipeline
  ###########
  create_dynamic_group_for_devops_pipln_in_compartment:
    type: boolean
    title: "Criar um Dynamic Group para pipelines de DevOps"
    description: | 
      Você precisa ser um administrador para fazer isso.

      Como alternativa, você pode fazer com que o administrador crie um grupo dinâmico para você. 
    default: true
    
  ####################  
  ## OKE 
  ####################
  
  k8s_version:
    type: string
    visible: false

  num_pool_workers:
    type: integer
    title: "Number of Worker Nodes"
    minimum: 1
    maximum: 1000
    required: true
    visible: true

  node_pool_shape:
    type: oci:core:instanceshape:name
    title: "Select a shape for the Worker Nodes instances"
    required: true
    dependsOn:
      compartmentId: compartment_ocid
    visible: true

  node_pool_node_shape_config_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    title: "Number of OCPUs"
    visible:
      and:
        - and:
          - true
        - or:
          - eq:
            - node_pool_shape 
            - "VM.Standard.E5.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A2.Flex"

  node_pool_node_shape_config_memory_in_gbs:
    type: integer
    minimum: 1
    maximum: 1024
    title: "Amount of memory (GB)"
    visible:
      and:
        - and:
          - true
        - or:
          - eq:
            - node_pool_shape 
            - "VM.Standard.E5.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A2.Flex"

  node_pool_name:
    type: string
    title: "Node Pool Name"
    required: true
    visible: true

  image_operating_system:
    type: enum
    title: "Image OS"
    enum:
      - "Oracle Linux"
    required: true
    visible: false

  image_operating_system_version:
    type: string
    required: true
    title: "Image OS Version"
    visible: false
  
  create_dynamic_group_for_nodes_in_compartment:
    type: boolean
    title: "Create Dynamic Group for Worker Nodes in the Compartment"
    required: true
    visible:
      and:
        - show_advanced

  existent_dynamic_group_for_nodes_in_compartment:
    type: string
    required: true
    title: "Existent Dynamic Group"
    visible:
      and:
        - and:
          - show_advanced
        - or:
          - create_compartment_policies
          - create_tenancy_policies
        - not:
          - create_dynamic_group_for_nodes_in_compartment
        
  create_compartment_policies:
    type: boolean
    title: "Create Compartment Policies"
    required: true
    visible:
      and:
        - show_advanced

  create_tenancy_policies:
    type: boolean
    title: "Create Tenancy Policies"
    required: true
    visible:
      and:
        - show_advanced


  ####################  
  ## API Gateway 
  ####################
  
  api_gateway_name:
    type: string
    title: "Nome do API Gateway"
    #description: "Nome do API Gateway a ser criado"
    #default: "API Gateway FT"
    required: true

  api_gateway_type:
    type: string
    title: "API Gateway Type"
    #default: "PUBLIC"
    visible: false

# Repository

  repository_is_immutable:
      type: boolean
      title: Respositório é Imutável?
      required: true

  repository_repository_type:
      type: string
      title: Tipo de Repositório
      required: true

    
  artifact_repository_display_name:
      type: string
      title: Nome do Respositório de Artefatos
      required: true

  container_repository_display_name:
    type: string
    title: Nome da Imagem de container 
    required: true

# Bucket

# Functions

  application_display_name:
      type: string
      title: "Nome do Aplicação no Functions"
      required: true

# Queue

  queue_display_name:
    type: string
    title: "Queue Name"
    required: true

# vault
  vault_display_name:
    type: string
    title: "Vault Name"
    required: true