FROM python:3.11 as dependency
WORKDIR /reqs
COPY requirements.txt /reqs
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11
WORKDIR /home/app
COPY msg_reader.py .
COPY --from=dependency /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/
ENV PYTHONUNBUFFERED=1
CMD ["python", "-u", "./msg_reader.py"]